source "http://rubygems.org"

gem 'rails', '~> 3.2.0'

group :development do
  gem 'sqlite3'
end

gem 'coffee-rails', '~> 3.2.1'
gem 'jquery-rails'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
gem 'therubyracer'
